version: '3.7'
services:
  flask:
    build:
      context: ./
      dockerfile: flaskdockerfile
    ports:
      - "5000:80"
  nginx:
    image: nginx:1.15.12
    volumes:
      - ./web/dist/web/:/var/www/front
      - ./nginx-site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4200:4200"
