all:
  children:
    vps:
      hosts:
        '1231':
          ansible_host: 1.1.1.1
          ansible_port: '33'
          ansible_user: root
          configured: 'no'
          host_id: 1
          hostname: '1231'
          interface: tun1
          ip_info:
            bogon: false
            city: Sanaa
            country: YE
            region: San'a'
          routes: []
        DO-ubuntu:
          DO-ubuntu: DO-ubuntu
          ansible_host: 128.199.32.219
          ansible_user: root
          configured: 'yes'
          host_id: 0
          hostname: DO-ubuntu
          interface: tun0
          ip_info:
            bogon: false
            city: Amsterdam
            country: NL
            region: North Holland
          routes:
          - destination: 0.0.0.0/0
            route: ''
            source: 127.0.0.1
          state: available
        ubuntu:
          ansible_host: 10.1.1.243
          configured: 'yes'
          host_id: 2
          hostname: ubuntu
          interface: tun2
          ip_info:
            bogon: true
          routes: []
          state: unreachable
          ubuntu: ubuntu
          user: root
