all:
  children:
    vps:
      hosts:
        ? ''
        : ansible_host: ''
          ansible_port: ''
          ansible_user: ''
          configured: 'no'
          host_id: 4
          hostname: ''
          interface: tun4
          ip_info:
            message: urllib.request.urlopen(http://ipinfo.io//json) catch exception
            status: error
          routes: []
        DO-ubuntu:
          DO-ubuntu: DO-ubuntu
          ansible_host: 128.199.32.219
          ansible_user: root
          configured: 'yes'
          host_id: 0
          hostname: DO-ubuntu
          interface: tun0
          ip_info:
            bogon: false
            city: Amsterdam
            country: NL
            region: North Holland
          routes: []
          state: unreachable
        asd:
          ansible_host: asd
          ansible_port: sad
          ansible_user: asd
          configured: 'no'
          host_id: 1
          hostname: asd
          interface: tun1
          ip_info:
            message: urllib.request.urlopen(http://ipinfo.io/asd/json) catch exception
            status: error
          routes: []
          state: unreachable
        cloudfare:
          ansible_host: 8.8.8.8
          ansible_port: '23'
          ansible_user: root
          configured: 'no'
          host_id: 6
          hostname: cloudfare
          interface: tun6
          ip_info:
            bogon: false
            city: Mountain View
            country: US
            region: California
          routes: []
        debian:
          ansible_host: 10.1.1.244
          ansible_port: ''
          ansible_user: root
          configured: 'no'
          host_id: 3
          hostname: debian
          interface: tun3
          ip_info:
            bogon: true
          routes: []
          state: unreachable
        google:
          ansible_host: 1.1.1.1
          ansible_port: '23'
          ansible_user: root
          configured: 'no'
          host_id: 5
          hostname: google
          interface: tun5
          ip_info:
            bogon: false
            city: Sanaa
            country: YE
            region: San'a'
          routes: []
        ubuntu:
          ansible_host: 10.1.1.243
          configured: 'yes'
          host_id: 2
          hostname: ubuntu
          interface: tun2
          ip_info:
            bogon: true
          routes: []
          state: unreachable
          ubuntu: ubuntu
          user: root
