all:
  children:
    vps:
      hosts:
        dasxzxc:
          ansible_host: 165.22.224.247
          ansible_user: root
          configured: 'yes'
          host_id: 1
          hostname: dasxzxc
          interface: tun1
          ip_info:
            bogon: false
            city: Toronto
            country: CA
            region: Ontario
          routes: []
          state: available
