all:
  children:
    vps:
      hosts:
        DO-ubuntu:
          ansible_host: 128.199.32.219
          ansible_user: root
          configured: 'yes'
          host_id: 0
          interface: tun0
          routes:
          - destination: 184.168.131.241
            route: ipinfo test route
            source: 127.0.0.1
          - destination: 216.239.32.211
            route: ipinfo test route
            source: 127.0.0.1
          - destination: 216.239.32.21
            route: ipinfo test route
            source: 127.0.0.1
          state: available
        debian:
          ansible_host: 10.1.1.244
          ansible_user: root
          host_id: 1
          interface: tun1
          routes: []
          state: available
        ubuntu:
          ansible_host: 10.1.1.243
          host_id: 2
          interface: tun2
          routes: []
          state: unreachable
          user: root
