all:
  children:
    vps:
      hosts:
        DO-ubuntu:
          ansible_host: 128.199.32.219
          ansible_user: root
          configured: 'yes'
          host_id: 0
          hostname: DO-ubuntu
          interface: tun0
          ip_info:
            bogon: false
            city: Amsterdam
            country: NL
            region: North Holland
          routes: []
          state: available
