all:
  children:
    vps:
      hosts:
        DO-debian-sgp:
          ansible_host: 128.199.199.181
          ansible_user: root
          configured: 'yes'
          host_id: 1
          hostname: DO-debian-sgp
          interface: tun1
          ip_info:
            bogon: false
            city: Singapore
            country: SG
            region: ''
          routes: []
          state: available
        DO-ubuntu-ams:
          ansible_host: 128.199.32.219
          ansible_user: root
          configured: 'yes'
          host_id: 0
          hostname: DO-ubuntu-ams
          interface: tun0
          ip_info:
            bogon: false
            city: Amsterdam
            country: NL
            region: North Holland
          routes: []
          state: available
