all:
  children:
    vps:
      hosts:
        feer:
          ansible_host: 165.22.224.247
          ansible_user: root
          configured: 'yes'
          host_id: 0
          hostname: feer
          interface: tun0
          ip_info:
            bogon: false
            city: Toronto
            country: CA
            region: Ontario
          routes: []
          state: available
