all:
  children:
    vps:
      hosts:
        DO-ubuntu:
          ansible_host: 128.199.32.219
          ansible_user: root
          configured: 'no'
          host_id: 0
          interface: tun0
          routes: []
          state: available
        ubuntu:
          ansible_host: 10.1.1.243
          host_id: 2
          interface: tun2
          routes: []
          state: unreachable
          user: root
