all:
  children:
    vps:
      hosts:
        debian:
          ansible_host: 10.1.1.244
          ansible_user: root
          host_id: 0
          interface: tun0
          routes:
          - destination: 66.61.36.66
            route: new route to hell
            source: 192.168.6.66
          state: available
        ubuntu:
          ansible_host: 10.1.1.243
          host_id: 1
          interface: tun1
          routes: []
          state: unreachable
          user: root
        zubuntu:
          asdf: 1
          host_id: 2
          interface: tun2
          pihas: 2
          routes: []
          state: unreachable
