all:
  children:
    vps:
      hosts:
        DO-ubuntu:
          DO-ubuntu: DO-ubuntu
          ansible_host: 128.199.32.219
          ansible_user: root
          configured: 'yes'
          host_id: 0
          interface: tun0
          ip_info:
            bogon: false
            city: Amsterdam
            country: NL
            region: North Holland
          routes: []
          state: unreachable
        ubuntu:
          ansible_host: 10.1.1.243
          configured: 'yes'
          host_id: 2
          interface: tun2
          ip_info:
            bogon: true
          routes: []
          state: unreachable
          ubuntu: ubuntu
          user: root
