all:
  children:
    vps:
      hosts:
        debian:
          ansible_ssh_host: 10.1.1.244
          host_id: 0
          interface: tun0
          routes:
          - destination: 66.61.36.66
            route: new route to hell
            source: 192.168.6.66
        ubuntu:
          ansible_ssh_host: 10.1.1.243
          host_id: 1
          interface: tun1
          routes:
          - 
          -
          user: root
