all:
  children:
    vps:
      hosts:
        DO-ubuntu:
          DO-ubuntu: DO-ubuntu
          ansible_host: 128.199.32.219
          ansible_user: root
          configured: 'yes'
          host_id: 0
          hostname: DO-ubuntu
          interface: tun0
          ip_info:
            bogon: false
            city: Amsterdam
            country: NL
            region: North Holland
          routes:
          - destination: 0.0.0.0/0
            route: ipinfo test route
            source: 127.0.0.1
          state: available
        new_host:
          ansible_host: 128.199.32.219
          ansible_user: root
          configured: 'no'
          host_id: 1
          interface: tun1
          routes: []
        new_new_host:
          ansible_host: 128.199.32.219
          ansible_user: root
          configured: 'no'
          host_id: 3
          interface: tun3
          routes: []
        ubuntu:
          ansible_host: 10.1.1.243
          configured: 'yes'
          host_id: 2
          hostname: ubuntu
          interface: tun2
          ip_info:
            bogon: true
          routes:
          - destination: 0.0.0.0/0
            route: ''
            source: 127.0.0.1
          state: unreachable
          ubuntu: ubuntu
          user: root
