all:
  children:
    vps:
      hosts:
        LondonUK:
          ansible_host: 159.65.52.167
          ansible_port: 22
          ansible_user: root
          configured: 'yes'
          host_id: 1
          hostname: LondonUK
          interface: tun1
          ip_info:
            bogon: false
            city: London
            country: GB
            region: England
          routes: []
          state: available
        london:
          ansible_host: 159.65.52.167
          ansible_user: root
          configured: 'yes'
          host_id: 0
          hostname: london
          interface: tun0
          ip_info:
            bogon: false
            city: London
            country: GB
            region: England
          routes: []
          state: available
