all:
  children:
    vps:
      hosts:
        sf:
          ansible_host: 159.65.111.134
          ansible_user: root
          configured: 'yes'
          host_id: 0
          hostname: sf
          interface: tun0
          ip_info:
            bogon: false
            city: Santa Clara
            country: US
            region: California
          routes: []
          state: available
