- hosts: vps
  remote_user: root
  tasks:

    - name: stop OpenVPN server for Systemd
      become: yes
      systemd:
        name: openvpn-server@server.service
        state: stopped
        enabled: no
        daemon_reload: yes
      when: ansible_service_mgr == 'systemd'

    - name: stop OpenVPN client for Systemd
      become: yes
      local_action:
        module: systemd
        state: stopped
        enabled: no
        daemon_reload: no
        name: openvpn-client@{{ ansible_hostname }}.service
      when: ansible_service_mgr == 'systemd'
