---
- hosts: vps
  remote_user: root
  # You have to specify arguments 'source' and 'destination' in playbook command
  # with --extra-vars, -e option:
  # $ ansible-playbook -l some_VPS_host roles/route.yml -e "source=192.168.0.2 \
  #                     destination=1.2.3.4/28"
  roles:
    - role: ovpn_server
