- hosts: all
  remote_user: root
  tasks:

    - name: set route on VPS
      script: "{{ inventory_dir }}/route.sh {{ source }} tun0" 
      tags:
        route

    - name: set local route
      become: yes
      local_action:
        module: script "{{ inventory_dir }}/route.sh" "{{ destination }}" "tun{{ groups['vps'].index(inventory_hostname) }}" 
      tags:
        route
