- hosts: all
  remote_user: root
  tasks:

    - name: set route on VPS
      command: ip route add "{{ source }}" dev tun0

    - name: set local route
      become: yes
      local_action:
        module: command ip route add "{{ destination }}" dev "tun{{ groups['vps'].index(inventory_hostname) }}"
 
