- name: copy client certificates to system directory
  become: yes
  local_action:
    module: copy
    src: "{{ inventory_dir }}/easyrsa/pki/{{ item }}"
    dest: /etc/openvpn/client/
  with_items:
    - "ca.crt"
    - "issued/client.crt"
    - "private/client.key"

- name: copy OpenVPN client to system directory
  become: yes
  local_action:
    module: template
    src: client.ovpn
    dest: "/etc/openvpn/client/{{ ansible_hostname }}.conf"
    force: yes

- name: start OpenVPN client for Systemd
  become: yes
  local_action:
    module: systemd
    state: restarted
    enabled: yes
    daemon_reload: yes
    name: openvpn-client@{{ ansible_hostname }}.service
  when: ansible_service_mgr == 'systemd'
