- name: install packages
  remote_user: root
  vars:
    nm:
      pacman: NetworkManager
      apt: network-manager

  package:
    name:
      - sudo
      - openvpn
      - "{{ nm[ ansible_pkg_mgr ] }}"
    state: present
  tags: 
    install
