- name: enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
  tags:
    nat

- name: enable MASQUERADE
  iptables:
    table: nat
    action: append 
    chain: POSTROUTING 
    source: 10.0.0.0/24
    jump: MASQUERADE
    state: present
  tags:
    nat
