- name: Make sure we have a 'wheel' group
  remote_user: root
  group:
    name: wheel
    state: present  

- name: Allow 'wheel' group to have passwordless sudo
  remote_user: root
  copy:
    src: sudoers 
    dest: /etc/sudoers
    state: present
    mode: 400
    owner: root
    group: root
    validate: visudo -cf %s  

- name: add ansible user to VPS
  remote_user: root
  user: 
    name: ansible
    state: present
    append: yes
    create_home: yes
    groups: wheel
    generate_ssh_key: yes
    ssh_key_type: ecdsa
    ssh_key_bits: 521

- name: get ssh public key
  remote_user: root
  local_action: shell cat $HOME/.ssh/*.pub
  register: pubkey
  when: pubkey is not defined
  # check statement 'when' above

- name: copy ssh autorized public keys 
  remote_user: root
  authorized_key:
    key: "{{ pubkey.stdout }}"
    user: ansible
    state: present
