- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present  

- name: Allow 'wheel' group to have passwordless sudo
  copy:
    src: sudoers 
    dest: /etc/sudoers
    mode: 400
    owner: root
    group: root
    validate: visudo -cf %s  

- name: add ansible user to VPS
  user: 
    name: ansible
    state: present
    append: yes
    create_home: yes
    groups: wheel
    generate_ssh_key: yes
    ssh_key_type: ecdsa
    ssh_key_bits: 521
