- hosts: test
  remote_user: root
  tasks:
    - name: add ansible user to VPN hosts
      user: 
        name: ansible
        state: present
        append: yes
        create_home: yes
        groups: wheel
        generate_ssh_key: yes
        ssh_key_type: ecdsa
        ssh_key_bits: 521

    - name: install packets for sudo
      pacman:
        name:
          - sudo
        state: present

    - name: allow wheel users use sudo
      template:
        src: ../templates/sudoers
        dest: /etc/sudoers
        validate: visudo -cf %s

    - name: set sshd_config for VPS
      template:
        src: ../templates/sshd_config
        dest: /etc/ssh/sshd_config

    - name: copy ssh autorized public keys 
      become_user: ansible
      become: yes
      template:
        src: /home/berkut/.ssh/id_ecdsa.pub
        dest: /home/ansible/.ssh/authorized_keys
        backup: yes
        mode: 0600

    - name: restart ssh daemon
      service:
        name: sshd
        enabled: yes
        state: restarted
