- hosts: all
  remote_user: root
  tasks:
    #---vvv---SUDO---vvv---#
    - name: install sudo for Archlinux
      package:
        name:
          - sudo
        state: present
    #---^^^---SUDO---^^^---#

    #---vvv---SSHD_config---vvv---#
    - name: set sshd_config for VPS
      vars:
        sftp_path: /usr/lib/ssh/sftp-server
      template:
        src: ../templates/sshd_config
        dest: /etc/ssh/sshd_config
      when: ansible_facts['distribution'] == 'Archlinux'

    - name: set sshd_config for VPS
      vars:
        sftp_path: /usr/lib/openssh/sftp-server
      template:
        src: ../templates/sshd_config
        dest: /etc/ssh/sshd_config
      when: ansible_facts['distribution'] == 'Ubuntu' or
            ansible_facts['distribution'] == 'Debian'

    - name: set sshd_config for VPS
      vars:
        sftp_path: /usr/libexec/openssh/sftp-server
      template:
        src: ../templates/sshd_config
        dest: /etc/ssh/sshd_config
      when: ansible_facts['distribution'] == 'CentOS'
    #---^^^---SSHD_config---^^^---#

    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present  

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: visudo -cf %s  

    - name: add ansible user to VPN hosts
      user: 
        name: ansible
        state: present
        append: yes
        create_home: yes
        groups: wheel
        generate_ssh_key: yes
        ssh_key_type: ecdsa
        ssh_key_bits: 521
    
    - name: get ssh public key
      local_action: shell cat $HOME/.ssh/*.pub
      register: pubkey
      when: pubkey is not defined

    - name: copy ssh autorized public keys 
      authorized_key:
        key: "{{ pubkey.stdout }}"
        user: ansible
        state: present

    - name: restart ssh daemon
      service:
        name: sshd
        enabled: yes
        state: restarted
